### PR TITLE
Add support for Svelte 4

### PR DESCRIPTION
**Pull request by Greenheart**
Seems like peerDependencies was all that needed to be updated.

I ran the recommended migration script and no changes were required.

`npx svelte-migrate@latest svelte-4`

Happy to receive any feedback and get this merged.

### CODE REVIEW

**Comment by PaulMaly** [comment]
Looks good to me, thanks. Please resolve the merge conflict after automatic dependabot PR and this one will fly. Seems  will be enough to just run migration script again.

**Comment by Greenheart** [comment]
Sure. The dependabot upgrade would already be handled by this PR, so this created extra work. I'll see if the merge conflict can be resolved smoothly though.

**Comment by Greenheart** [comment]
Done. Thanks for maintaining this project! :)

Been really useful for my small starter template https://github.com/Greenheart/svelte-encrypted-spa

**Comment by PaulMaly** [comment]
Npm version published as well. Thanks for this PR.

**Pull request merged**
